
#include <stdio.h>
#include <limits.h>

int		main(void)
{
	int		d;

	d = 42;
	printf("d :\n");
	printf("");
	printf("\n");
	printf("%d", d);
	printf("\n%d", d);
	printf("\nEssai : 		|%d|\n", d);
	printf("Double : 		|%d%d|\n", d, d);
	printf("Larg 16 :		|%16d|\n", d);
	printf("*Larg 16 :		|%*d|\n",16, d);
	printf("larg 6 :		|%6d|\n", d);
	printf("*larg 6 :		|%*d|\n",6, d);
	printf("*Larg -16 :		|%*d|\n",-16, d);
	printf("Flag '-' : 		|%-16d|\n", d);
	printf("Flag '-' x3 :		|%---16d|\n", d);
	printf("Flag '0' : 		|%016d|\n", d);
	printf("Flag '0' x3 :		|%00016d|\n", d);
	printf("-d :	 		|%016d|\n", -d);
	printf("8'0' -d : 		|%08d|\n", -d);
	printf("8'-' -d : 		|%-8d|\n",-d);
	printf("P8 -d :			|%.8d|\n", -d);
	printf("P3 -d :			|%.3d|\n", -d);
	printf("9'0'P8 -d :		|%09.8d|\n", -d);
	printf("Prec 8 :		|%.8d|\n", d);
	printf("*Prec 8 :		|%.*d|\n",8, d);
	printf("*prec -8 :		|%.*d|\n",-8, d);
	printf("Prec 0 :		|%.0d|\n", d);
	printf("*Prec 0 :		|%.*d|\n",0, d);
	printf("Prec . :		|%.d|\n", d);
	printf("prec 15 :		|%.15d|\n", d);
	printf("*prec 15 :		|%.*d|\n",15, d);
	printf("*Prec 8 :		|%.*d|\n",8, d);
	printf("L && P :		|%16.8d|\n", d);
	printf("*L && *P :		|%*.*d|\n",16, 8, d);
	printf("l && P :		|%4.8d|\n", d);
	printf("*l && *P :		|%*.*d|\n",4, 8, d);
	printf("L && p :		|%16.18d|\n", d);
	printf("*L && *p :		|%*.*d|\n",16, 18, d);
	printf("l && p :		|%6.18d|\n", d);
	printf("*l && *p :		|%*.*d|\n",6, 18, d);
	printf("INTMAX - :		|%-*d|\n",30, INT_MAX);
	printf("INTMAX L30P20 :		|%*.*d|\n",30, 20, INT_MAX);
	printf("INTMIN - :		|%-*d|\n",30, INT_MIN);
	printf("INTMIN L30P20 :		|%*.*d|\n",30, 20, INT_MIN);
	printf("\n--------DOUBLE------:\n\n");
	printf("D Larg 16 :		|%16d%16d|\n", d, d);
	printf("D *Larg 16 :		|%*d%*d|\n",16, d,16, d);
	printf("D larg 6 :		|%6d%6d|\n", d, d);
	printf("D *larg 6 :		|%*d%*d|\n",6, d,6, d);
	printf("D *Larg -16 :		|%*d%*d|\n",-16, d,-16, d);
	printf("D Flag '-' : 		|%-16d%-16d|\n", d, d);
	printf("D Flag '-' x3 :		|%---16d%---16d|\n", d, d);
	printf("D Prec 8 :		|%.8d%.8d|\n", d, d);
	printf("D *Prec 8 :		|%.*d%.*d|\n",8, d,8, d);
	printf("D *prec -8 :		|%.*d%.*d|\n",-8, d,-8, d);
	printf("D Prec 0 :		|%.0d%.0d|\n", d, d);
	printf("D *Prec 0 :		|%.*d%.*d|\n",0, d,0, d);
	printf("D Prec . :		|%.d%.d|\n", d, d);
	printf("D prec 15 :		|%.15d%.15d|\n", d, d);
	printf("D *prec 15 :		|%.*d%.*d|\n",15, d,15, d);
	printf("D *Prec 8 :		|%.*d%.*d|\n",8, d,8, d);
	printf("D L && P :		|%16.8d%16.8d|\n", d, d);
	printf("D *L && *P :		|%*.*d%*.*d|\n",16, 8, d,16, 8, d);
	printf("D l && P :		|%4.8d%4.8d|\n", d, d);
	printf("D *l && *P :		|%*.*d%*.*d|\n",4, 8, d,4, 8, d);
	printf("D L && p :		|%16.18d%16.18d|\n", d, d);
	printf("D *L && *p :		|%*.*d%*.*d|\n",16, 18, d,16, 18, d);
	printf("D l && p :		|%6.18d%6.18d|\n", d, d);
	printf("D *l && *p :		|%*.*d%*.*d|\n",6, 18, d,6, 18, d);
	printf("-------------d = 0----------\n");
	d = 0;
	printf("Larg 16 :		|%16d|\n", d);
	printf("*Larg 16 :		|%*d|\n",16, d);
	printf("larg 6 :		|%6d|\n", d);
	printf("*larg 6 :		|%*d|\n",6, d);
	printf("*Larg -16 :		|%*d|\n",-16, d);
	printf("Flag '-' : 		|%-16d|\n", d);
	printf("Flag '-' x3 :		|%---16d|\n", d);
	printf("Flag '0' : 		|%016d|\n", d);
	printf("Flag '0' x3 :		|%00016d|\n", d);
	printf("-d :	 		|%016d|\n", -d);
	printf("8'0' -d : 		|%08d|\n", -d);
	printf("8'-' -d : 		|%-8d|\n",-d);
	printf("P8 -d :			|%.8d|\n", -d);
	printf("P3 -d :			|%.3d|\n", -d);
	printf("9'0'P8 -d :		|%09.8d|\n", -d);
	printf("Prec 8 :		|%.8d|\n", d);
	printf("*Prec 8 :		|%.*d|\n",8, d);
	printf("*prec -8 :		|%.*d|\n",-8, d);
	printf("Prec 0 :		|%.0d|\n", d);
	printf("*Prec 0 :		|%.*d|\n",0, d);
	printf("Prec . :		|%.d|\n", d);
	printf("prec 15 :		|%.15d|\n", d);
	printf("*prec 15 :		|%.*d|\n",15, d);
	printf("*Prec 8 :		|%.*d|\n",8, d);
	printf("L && P :		|%16.8d|\n", d);
	printf("*L && *P :		|%*.*d|\n",16, 8, d);
	printf("l && P :		|%4.8d|\n", d);
	printf("*l && *P :		|%*.*d|\n",4, 8, d);
	printf("L && p :		|%16.18d|\n", d);
	printf("*L && *p :		|%*.*d|\n",16, 18, d);
	printf("l && p :		|%6.18d|\n", d);
	printf("*l && *p :		|%*.*d|\n",6, 18, d);
	return (1);
}
