
#include "ft_printf.h"
#include <limits.h>

int		main(void)
{
	unsigned int		d;

	d = 4242420;
	ft_printf("\n-----------TEST x----------\n");
	ft_printf("d :\n");
	ft_printf("");
	ft_printf("\n");
	ft_printf("%x", d);
	ft_printf("\n%x", d);
	ft_printf("\nEssai : 		|%x|\n", d);
	ft_printf("Double : 		|%x%x|\n", d, d);
	ft_printf("Larg 16 :		|%16x|\n", d);
	ft_printf("*Larg 16 :		|%*x|\n",16, d);
	ft_printf("larg 6 :		|%6x|\n", d);
	ft_printf("*larg 6 :		|%*x|\n",6, d);
	ft_printf("*Larg -16 :		|%*x|\n",-16, d);
	ft_printf("Flag '-' : 		|%-16x|\n", d);
	ft_printf("Flag '-' x3 :		|%---16x|\n", d);
	ft_printf("Flag '0' : 		|%016x|\n", d);
	ft_printf("Flag '0' x3 :		|%00016x|\n", d);
	ft_printf("Prec 8 :		|%.8x|\n", d);
	ft_printf("*Prec 8 :		|%.*x|\n",8, d);
	ft_printf("*prec -8 :		|%.*x|\n",-8, d);
	ft_printf("Prec 0 :		|%.0x|\n", d);
	ft_printf("*Prec 0 :		|%.*x|\n",0, d);
	ft_printf("Prec . :		|%.x|\n", d);
	ft_printf("prec 15 :		|%.15x|\n", d);
	ft_printf("*prec 15 :		|%.*x|\n",15, d);
	ft_printf("*Prec 8 :		|%.*x|\n",8, d);
	ft_printf("L && P :		|%16.8x|\n", d);
	ft_printf("*L && *P :		|%*.*x|\n",16, 8, d);
	ft_printf("l && P :		|%4.8x|\n", d);
	ft_printf("*l && *P :		|%*.*x|\n",4, 8, d);
	ft_printf("L && p :		|%16.18x|\n", d);
	ft_printf("*L && *p :		|%*.*x|\n",16, 18, d);
	ft_printf("l && p :		|%6.18x|\n", d);
	ft_printf("*l && *p :		|%*.*x|\n",6, 18, d);
	ft_printf("UINTMAX - :		|%-*x|\n",30, UINT_MAX);
	ft_printf("UINTMAX L30P20 :	|%*.*x|\n",30, 20, UINT_MAX);
	ft_printf("0 - :			|%-*x|\n",30, 0);
	ft_printf("0 L30P20 :		|%*.*x|\n",30, 20, 0);
	ft_printf("\n--------DOUBLE------:\n\n");
	ft_printf("D Larg 16 :		|%16x%16x|\n", d, d);
	ft_printf("D *Larg 16 :		|%*x%*x|\n",16, d,16, d);
	ft_printf("D larg 6 :		|%6x%6x|\n", d, d);
	ft_printf("D *larg 6 :		|%*x%*x|\n",6, d,6, d);
	ft_printf("D *Larg -16 :		|%*x%*x|\n",-16, d,-16, d);
	ft_printf("D Flag '-' : 		|%-16x%-16x|\n", d, d);
	ft_printf("D Flag '-' x3 :		|%---16x%---16x|\n", d, d);
	ft_printf("D Prec 8 :		|%.8x%.8x|\n", d, d);
	ft_printf("D *Prec 8 :		|%.*x%.*x|\n",8, d,8, d);
	ft_printf("D *prec -8 :		|%.*x%.*x|\n",-8, d,-8, d);
	ft_printf("D Prec 0 :		|%.0x%.0x|\n", d, d);
	ft_printf("D *Prec 0 :		|%.*x%.*x|\n",0, d,0, d);
	ft_printf("D Prec . :		|%.x%.x|\n", d, d);
	ft_printf("D prec 15 :		|%.15x%.15x|\n", d, d);
	ft_printf("D *prec 15 :		|%.*x%.*x|\n",15, d,15, d);
	ft_printf("D *Prec 8 :		|%.*x%.*x|\n",8, d,8, d);
	ft_printf("D L && P :		|%16.8x%16.8x|\n", d, d);
	ft_printf("D *L && *P :		|%*.*x%*.*x|\n",16, 8, d,16, 8, d);
	ft_printf("D l && P :		|%4.8x%4.8x|\n", d, d);
	ft_printf("D *l && *P :		|%*.*x%*.*x|\n",4, 8, d,4, 8, d);
	ft_printf("D L && p :		|%16.18x%16.18x|\n", d, d);
	ft_printf("D *L && *p :		|%*.*x%*.*x|\n",16, 18, d,16, 18, d);
	ft_printf("D l && p :		|%6.18x%6.18x|\n", d, d);
	ft_printf("D *l && *p :		|%*.*x%*.*x|\n",6, 18, d,6, 18, d);
	ft_printf("\n-----------TEST X----------\n");
	ft_printf("\nEssai : 		|%X|\n", d);
	ft_printf("Double : 		|%X%X|\n", d, d);
	ft_printf("Larg 16 :		|%16X|\n", d);
	ft_printf("*Larg 16 :		|%*X|\n",16, d);
	ft_printf("larg 6 :		|%6X|\n", d);
	ft_printf("*larg 6 :		|%*X|\n",6, d);
	ft_printf("*Larg -16 :		|%*X|\n",-16, d);
	ft_printf("Flag '-' : 		|%-16X|\n", d);
	ft_printf("Flag '-' X3 :		|%---16X|\n", d);
	ft_printf("Flag '0' : 		|%016X|\n", d);
	ft_printf("Flag '0' X3 :		|%00016X|\n", d);
	ft_printf("Prec 8 :		|%.8X|\n", d);
	ft_printf("*Prec 8 :		|%.*X|\n",8, d);
	ft_printf("*prec -8 :		|%.*X|\n",-8, d);
	ft_printf("Prec 0 :		|%.0X|\n", d);
	ft_printf("*Prec 0 :		|%.*X|\n",0, d);
	ft_printf("Prec . :		|%.X|\n", d);
	ft_printf("prec 15 :		|%.15X|\n", d);
	ft_printf("*prec 15 :		|%.*X|\n",15, d);
	ft_printf("*Prec 8 :		|%.*X|\n",8, d);
	ft_printf("L && P :		|%16.8X|\n", d);
	ft_printf("*L && *P :		|%*.*X|\n",16, 8, d);
	ft_printf("l && P :		|%4.8X|\n", d);
	ft_printf("*l && *P :		|%*.*X|\n",4, 8, d);
	ft_printf("L && p :		|%16.18X|\n", d);
	ft_printf("*L && *p :		|%*.*X|\n",16, 18, d);
	ft_printf("l && p :		|%6.18X|\n", d);
	ft_printf("*l && *p :		|%*.*X|\n",6, 18, d);
	ft_printf("UINTMAX - :		|%-*X|\n",30, UINT_MAX);
	ft_printf("UINTMAX L30P20 :	|%*.*X|\n",30, 20, UINT_MAX);
	ft_printf("0 - :			|%-*X|\n",30, 0);
	ft_printf("0 L30P20 :		|%*.*X|\n",30, 20, 0);
	ft_printf("\n--------DOUBLE------:\n\n");
	ft_printf("D Larg 16 :		|%16X%16X|\n", d, d);
	ft_printf("D *Larg 16 :		|%*X%*X|\n",16, d,16, d);
	ft_printf("D larg 6 :		|%6X%6X|\n", d, d);
	ft_printf("D *larg 6 :		|%*X%*X|\n",6, d,6, d);
	ft_printf("D *Larg -16 :		|%*X%*X|\n",-16, d,-16, d);
	ft_printf("D Flag '-' : 		|%-16X%-16X|\n", d, d);
	ft_printf("D Flag '-' X3 :		|%---16X%---16X|\n", d, d);
	ft_printf("D Prec 8 :		|%.8X%.8X|\n", d, d);
	ft_printf("D *Prec 8 :		|%.*X%.*X|\n",8, d,8, d);
	ft_printf("D *prec -8 :		|%.*X%.*X|\n",-8, d,-8, d);
	ft_printf("D Prec 0 :		|%.0X%.0X|\n", d, d);
	ft_printf("D *Prec 0 :		|%.*X%.*X|\n",0, d,0, d);
	ft_printf("D Prec . :		|%.X%.X|\n", d, d);
	ft_printf("D prec 15 :		|%.15X%.15X|\n", d, d);
	ft_printf("D *prec 15 :		|%.*X%.*X|\n",15, d,15, d);
	ft_printf("D *Prec 8 :		|%.*X%.*X|\n",8, d,8, d);
	ft_printf("D L && P :		|%16.8X%16.8X|\n", d, d);
	ft_printf("D *L && *P :		|%*.*X%*.*X|\n",16, 8, d,16, 8, d);
	ft_printf("D l && P :		|%4.8X%4.8X|\n", d, d);
	ft_printf("D *l && *P :		|%*.*X%*.*X|\n",4, 8, d,4, 8, d);
	ft_printf("D L && p :		|%16.18X%16.18X|\n", d, d);
	ft_printf("D *L && *p :		|%*.*X%*.*X|\n",16, 18, d,16, 18, d);
	ft_printf("D l && p :		|%6.18X%6.18X|\n", d, d);
	ft_printf("D *l && *p :		|%*.*X%*.*X|\n",6, 18, d,6, 18, d);
	ft_printf("-------------x = 0----------\n");
	d = 0;
	ft_printf("Larg 16 :		|%16x|\n", d);
	ft_printf("*Larg 16 :		|%*x|\n",16, d);
	ft_printf("larg 6 :		|%6x|\n", d);
	ft_printf("*larg 6 :		|%*x|\n",6, d);
	ft_printf("*Larg -16 :		|%*x|\n",-16, d);
	ft_printf("Flag '-' : 		|%-16x|\n", d);
	ft_printf("Flag '-' x3 :		|%---16x|\n", d);
	ft_printf("Flag '0' : 		|%016x|\n", d);
	ft_printf("Flag '0' x3 :		|%00016x|\n", d);
	ft_printf("Prec 8 :		|%.8x|\n", d);
	ft_printf("*Prec 8 :		|%.*x|\n",8, d);
	ft_printf("*prec -8 :		|%.*x|\n",-8, d);
	ft_printf("Prec 0 :		|%.0x|\n", d);
	ft_printf("*Prec 0 :		|%.*x|\n",0, d);
	ft_printf("Prec . :		|%.x|\n", d);
	ft_printf("prec 15 :		|%.15x|\n", d);
	ft_printf("*prec 15 :		|%.*x|\n",15, d);
	ft_printf("*Prec 8 :		|%.*x|\n",8, d);
	ft_printf("L && P :		|%16.8x|\n", d);
	ft_printf("*L && *P :		|%*.*x|\n",16, 8, d);
	ft_printf("l && P :		|%4.8x|\n", d);
	ft_printf("*l && *P :		|%*.*x|\n",4, 8, d);
	ft_printf("L && p :		|%16.18x|\n", d);
	ft_printf("*L && *p :		|%*.*x|\n",16, 18, d);
	ft_printf("l && p :		|%6.18x|\n", d);
	ft_printf("*l && *p :		|%*.*x|\n",6, 18, d);
	return (1);
}
